[tools]
#--- Format
# Opinionated Code Formatter.
prettier = "latest"
# A shell formatter.
shfmt = "latest"

#--- Lint
# A static analysis tool for shell scripts.
shellcheck = "latest"


[tasks.fmt]
description = 'Format all files'
depends = ['fmt:*']

[tasks.lint]
description = 'Run all linters'
depends = ['lint:*']

[tasks.default]
description = 'Run all formatters and linters'
depends = ['fmt', 'lint']

[tasks.'fmt:markdown']
description = 'Format markdown files'
sources = ['**/*.md']
run = 'prettier --write "**/*.md"'

[tasks.'fmt:shell']
description = 'Format shell scripts'
sources = ['**/bin/*', '**/sbin/*', '**/runsvdir/all/**/run']
run = '''
{% for file in task_source_files() %}
    shfmt --write --indent 4 --simplify {{ file }}
    chmod +x {{ file }}
{% endfor %}
'''

[tasks.'lint:markdown']
description = 'Lint markdown files'
wait_for = ['fmt:markdown']
sources = ['**/*.md']
run = 'prettier --check "**/*.md"'

[tasks.'lint:shell']
description = 'Lint shell scripts'
wait_for = ['fmt:shell']
sources = ['**/bin/*', '**/sbin/*', '**/runsvdir/all/**/run']
run = 'shellcheck -x {{ task_source_files() | join(sep=" ") }}'

[tasks.'lint:xml']
description = 'Lint XML files'
sources = ['uid/dbus-1/system.d/*.conf']
run = 'xmllint --noout {{ task_source_files() | join(sep=" ") }}'
